<a href="https://colab.research.google.com/github/jihyebook-star/Week1-Intro-to-Python/blob/Assignment0/Introduction_to_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# PYTHON INTRODUCTION

#                                                      Table Of Content
1.introdution

     1.1 What is Python
     
2.Data types

     2.1 variables
     2.2 Numbers
     2.3 Strings
     2.4 Lists
     2.5 Dictionaries
     2.6 Tuples
     2.7 Sets
   
3.Comparison operators

4.If-Else statement

5.For Loop and While loop

6.Functions

7.Lambda functions

     7.1 Map()
     7.2 Filter()
   
8.File I/O

9.Pandas liberary introduction

10.Series

     10.1 From ndarray
     10.2 From dict
     10.3 From scalar value
     10.4 Series is ndarray-like
     10.5 Series is dict-like
     10.6 Vectorized operations and label alignment with series
   
11.Data frames

     11.1 From dict of series or dicts
     11.2 from dict of ndarrays/lists
     11.3 from a list of dicts
     11.4 from a list of tuples
     11.5 Alternate constructors
     11.6 Column selection, addition, deletion
     11.7 Indexing/ selection
     11.8 Data alignment
     11.9 transposing

# 1. Introduction

# Jihye Kim's Examples

## 0.1 Rules of Operation

- Rule of precedence

  1. Parenthesis (#1 priority)
  2. Exponentiation
  * the right-most operator gets to be recognized first

  example: 3* 1** = 3 (not 27)

## 0.2 File paths

* Absolute file path: if one wants to find assignment.py file in IAT360 folder in CourseProjects folder > /Users/yourname/CourseProjects/IAT360/assignment.py
* Relative file path: a link that directs to a file location on the page in which it's located

## 1.1 What is python

Guido Van Rossum developed the Python language in the late 1980s. In contrast to other popular languages such as C, C++, Java, and C#, Python strives to provide a simple but powerful syntax.It is open source general purpose language with great interactive environment.It provides all the three types of programming features Object Oriented, Procedural and Functional.It is used by many of the most highly productive professional programmers.Moreover, Python can also become a common language for production of web based analytics product. A few of the places that use Python extensively are Google, the New York Stock Exchange, Industrial Light,Magic etc.
#### Important features of Python:
 -  Built-in high level data types: strings, lists, dictionaries, etc.
 -  The usual control structures: if, if-else, if-elif-else, while, plus a powerful collection iterator (for).
 -  Multiple levels of organizational structure: functions, classes, modules, and  packages. These assist in organizing code. An excellent and large example is the Python standard library.
 - Compile on the fly to byte code -- Source code is compiled to byte code without a separate compile step. Source code modules can also be "pre-compiled" to byte code files.
 - Object-oriented -- Python provides a consistent way to use objects: everything is an object. And, in Python it is easy to implement new object types (called classes in object-oriented programming).
 - Extensions in C and C++ -- Extension modules and extension types can be written by hand. There are also tools that help with this, for example, SWIG, sip, Pyrex

# 2. Data types

There are various data types in Python. Some of the important types are listed below.

## 2.1 Variables

 - Python variables do not need explicit declaration to reserve memory space.
 - The declaration happens automatically when you assign a value to a variable.
 - The equal sign = is used to assign values to variables.
  
  Some examples are given as follows:

In [77]:
area = 200.30  #float type variable
Distance = 100 #integer type variabe
name = 'Sara' #string type variable
x = "Hello"
y = 10.05

#print all values
print(area)
print(Distance)
print(name)
print(x)
print(y)

200.3
100
Sara
Hello
10.05

## 2.2 Numbers

 - This data type store numeric values
 - Numbers are immutable data types (Immutable data types means values cannot be changed after it is created)

  Some examples are given as follows:

In [78]:
5 #integer

5

In [79]:
10+10 #integer

20

In [80]:
5.5+5.5 #float

11.0

In [81]:
5**2 #exponent

25

## 2.3 Strings

 - Strings in Python are identified as a contiguous set of characters represented in the quotation marks.
 - Python allows either pair of single or double quotes.
 - Strings are immutable.
 - Python doesn't support Char data type.It will beas string of length one in python.

In [82]:
Course="Artificial Intelligence"
name='Sara'
print(name, Course)

Sara Artificial Intelligence

### Access values in strings

 - we can access a specific character or range of characters from strings.
 - Subsets of strings can be taken using the slice operator [] and [:] with indexes starting from 0.

 Some examples are listed below:

In [83]:
stringVariable = 'Hello World'

print("stringVariable[0]:", stringVariable[0])
print("stringVariable[1:5]:", stringVariable[1:5])

stringVariable[0]: H
stringVariable[1:5]: ello

### Updating string

 - Value of string can be changed or updated by assigning a new value to it.
 - New value must have same data type as previous value.
 - For this purpose '+' operator is used as follows:

In [84]:
stringVariable ="Hello World "
stringVariable = stringVariable[:6]+"Python"


print("updated string:",stringVariable)

updated string: Hello Python

### Delete string

 - we can delete the value of string by just deleteing its object.
 - 'del' keyword is used for this purpose

  It would be cleared by using following example:

In [85]:
stringVariable ="Hello World "
print(stringVariable)
del stringVariable

Hello World

### String special operators

 - some special operators are used in Python to perform different opertions.
   These are given below:

#### String Concatenation

 - To concatenate the strings we used '+' operator.

    Following are the examples of concatenation:

In [86]:
stringvalue1="machine"
stringvalue2="learning"
print(stringvalue1+stringvalue2)

machinelearning

#### Repitition

 - '*' symbol is used for repitition.

In [87]:
stringvalue="Assignment"
print(stringvalue*2)

AssignmentAssignment

#### Use of [] symbol

 - '[]'symbol give the character of string at given index.

In [88]:
Stringvalue="Machine Learning"
print(Stringvalue[1])

a

#### Use of [:] symbol

 - [:] is used to get substring from string.

In [89]:
stringvalue="Hello"
print(stringvalue [1:3])

el

#### use of 'in'

 - 'in' is used to check the existance of character in string.
 - It returns TRUE if given character exist in string,otherwise FALSE.

In [90]:
Stringvalue="Hello"
print('H' in Stringvalue)

True

#### Use of "not in"

 - 'not in' returns true if given character is not in string,otherwise false.

In [91]:
Stringvalue="Hello"
print('G' not in Stringvalue)

True

### String formatting operator

 - Python uses C-style string formatting to create new, formatted strings.
 - The "%" operator is used to format in print statement.

See following examples:

In [92]:
print("My name is %s and weight is %d kg!" % ("Sara", 21))

My name is Sara and weight is 21 kg!

## 2.4 Lists

 - Multiple types of data can be stored in a list.
 - A list contains items separated by commas and enclosed within square brackets [].
 - Individual elements of a list can be changed
 - list indices start with 0 just like arrays.

In [93]:
list1 = [ 'Mary', 2000 ]

print(list1) # Prints complete list

['Mary', 2000]

### Accessing values in list

 - Square brackets are used to access the values of a list
 - We can access specific values or range of values from a list

In [94]:
list1 = [ 'Physics' , 'Chemistry' , 1857, 3290]
list2 = [1,2,3,4,5,6,7]

print("list1[0]: ", list1[0])
print("list2[1:5]: ", list2[1:5])

list1[0]:  Physics
list2[1:5]:  [2, 3, 4, 5]

### Updating list

 - Value of string can be changed or updated by assigning a new value to it.
 - we can update single or multiple elements of a list by giving slice on left hand of the assignment operator.
 - we can also update list by using append() function.

In [95]:
list1=["dell","Hp","Apple"]
list1[1]="samsung"
print(list1)

list1.append('acer')
print(list1)

['dell', 'samsung', 'Apple']
['dell', 'samsung', 'Apple', 'acer']

### Delete List Element

- we can delete the element of list by using del keyword or remove()function.
- 'del' keyword is used when you know the position or index of element to be deleted.
- remove() function can be used when you don't know the postion of element to be removed.

  It would be cleared by using following example:

In [96]:
list1=["dell","Hp","Apple"]
print(list1) # Prints complete list
del list1[1]
print("After deleting the value ")
print(list1)

['dell', 'Hp', 'Apple']
After deleting the value
['dell', 'Apple']

In [97]:
list1=["dell","Hp","Apple"]
print(list1) # Prints complete list

list1.remove('Hp')
print("After deleting the value ")
print(list1)

['dell', 'Hp', 'Apple']
After deleting the value
['dell', 'Apple']

## 2.5 Dictionaries

 - Dictionary is an unordered set of key: value pairs, with the requirement that the keys are unique (within one dictionary).
 - Each key is seperated by colon(:) from its value.
 - Each item is seperated with comma(,).
 - A pair of braces creates an empty dictionary: {}.
 - Python's dictionaries are kind of hash-table type.
 - A dictionary key can be almost any Python type, but are usually numbers or strings. Values, on the other hand, can be any       arbitrary Python object.
 - Dictionaries are enclosed by curly braces ({ }) and values can be assigned and accessed using square braces ([])
 - Dictionaries have no concept of order among elements. It is incorrect to say that the elements are "out of order"; they are simply unordered

## Accessing value in dictionary

- Square brackets [] along with the key are used to access its value.

In [98]:
dict1 = {'Name':"Sara" , "Department" : "SIAT", "Batch":2023}
print(dict1['Name'])

Sara

### Updating Dictionary

- we can update values in dictionary
- we can also add new values in dictionary

Some examples are given below:

In [99]:
dict1 = {'Name':"Sara" , "Department" : "SIAT", "Batch":2023}
print(dict1)
dict1['Batch']="S23"
print(dict1)

{'Name': 'Sara', 'Department': 'SIAT', 'Batch': 2023}
{'Name': 'Sara', 'Department': 'SIAT', 'Batch': 'S23'}

### Delete Dictionary element

- we can delete elements of dictionary as well as complete content of dictionary.
- To delete single element del keyword is used.
- clear() function  is used to remove complete dictionary.

 Some examples are as follows:

In [100]:
dict1 = {'Name':"Sara" , "Department" : "SIAT", "Batch":2023}
print(dict1)

del dict1['Batch']
print(dict1)

{'Name': 'Sara', 'Department': 'SIAT', 'Batch': 2023}
{'Name': 'Sara', 'Department': 'SIAT'}

In [101]:
dict1 = {'Name':"Sara" , "Department" : "SIAT", "Batch":2023}
dict1.clear()
print(dict1)

{}

## 2.6 Tuples

 - A tuple is another sequence data type that is similar to the list.
 - A tuple consists of a number of values separated by commas. Unlike lists, however, tuples are enclosed within parenthesis.
 - The main difference between lists and tuples are − Lists are enclosed in brackets ( [ ] ) and their elements and size can be  changed, while tuples are enclosed in parentheses ( ( ) ) and cannot be updated. Tuples can be thought of as read-only lists.   
 - It can also have multiple data type values.

  For example:

### Accessing values in Tuples

- Square brackets [] along with the index are used to access its value.

In [102]:
tuple1 = ( 'simon','sara' , '20', 'saira40')

print(tuple1)
print(tuple1[1:3])

('simon', 'sara', '20', 'saira40')
('sara', '20')

### Updating Tuples

- Tuples are immutable means we cannot change the value of tuple.
- It is read only.
- we are able to take portions of tuples to make a new tuple.

In [103]:
tuple1=('sun','mon','tue','wed','thur','fri' , 'sat')
tuple2=(1,2,3,4,5,6,7)
print(tuple1)
print(tuple2)
tuple3=(tuple1+tuple2)
print(tuple3)

('sun', 'mon', 'tue', 'wed', 'thur', 'fri', 'sat')
(1, 2, 3, 4, 5, 6, 7)
('sun', 'mon', 'tue', 'wed', 'thur', 'fri', 'sat', 1, 2, 3, 4, 5, 6, 7)

### Delete tuple elements

- we cannot delete single elements of tuple because they cannot be updated.
- To delete entire elements del keyword is used.

 Some examples are as follows:

In [104]:
tuple1=('sun','mon','tue','wed','thur','fri' , 'sat')
tuple2=(1,2,3,4,5,6,7)
print(tuple1)
print(tuple2)
del(tuple1)
print(tuple1)

('sun', 'mon', 'tue', 'wed', 'thur', 'fri', 'sat')
(1, 2, 3, 4, 5, 6, 7)

NameError: name 'tuple1' is not defined

# 2.7 Sets

 - A set is an unordered collection in which each value occurs at most once.
 - You can use curly braces to give an expression whose value is a set.
 - Python prints sets using curly braces.
 - Every value in a set is immutable but the set itself is immutable we can add o remove items from it.
 - Sets can be used to perform mathematical operations like union,intersection,etc
 - Empty set will be written as {}.
 - We can also make a set from a list using set() function.
 - Data type can be found using type() function.
 - add() is used to add single value, update() is used for adding multiple values.
 - update() function can take tuple,string,list or other set as argument.
 - discard() and remove() are used to delete specific item from list.
 - discard() will not raise an error if item doesn't exist.
 - remove() will raise an error if item doesn't exist in set.
 - The cardinality of a set S is the number of elements in the set.
 - In Python, the cardinality of a set is obtained using the function len(·).

In [105]:
#list
list1=[1,2,3,4,5]

print(type(list1))

my_set=set(list1)

print(type(my_set))

#set of integers
my_set={1,2,3}
print(my_set)

#set of mixed data types
my_set={1, "Hello"}

#adding a single value
my_set.add("D")

#adding multiple values
my_set.update(list1)
print(my_set)


my_set.discard('G') #it will not raise an error
my_set.remove('G') #it will raise an error

<class 'list'>
<class 'set'>
{1, 2, 3}
{1, 2, 3, 4, 'D', 5, 'Hello'}

KeyError: 'G'

# 3.Comparison Operators

 - Comparison operators are used to compare values and return TRUE/FALSE according to the situation.
 - Python defines the following comparison operators:

### Less than operator  (<)

In [106]:
10<17

True

### Less than equal to operator (<=)

In [107]:
15<=10

False

### Equal to operatoe (==)

In [108]:
16==16

True

In [109]:
"Sara"=="sara"

False

In [110]:
"ALI"=="ALI"

True

### Not equal to operator (!=)

In [111]:
3!=5

True

### OR Operator

In [112]:
(10==10)or(10<17)

True

### And operator

In [113]:
(10==10)and (10<17)

True

# 4.If else statement

 - The if–else is used to make choices in Python code.
 - This is a compound statement.
 - The syntax is:
 - if c o n d i t i o n
          action −1
  else :
          action −2
 - The indentation is required

In [114]:
x = 3
if x > 0:
    print(" sunday is wonderful")
else :
    print(" Monday is Good ")

 sunday is wonderful

In [115]:
if 25 % 2:
  print("Even")
else:
  print("Odd")

Even

# 5.For and while loop

- Python has for and while loop for iteration,used when we want to perfrom a specific task repeatedly.

### For loop

- The for statement is used to iterate over the elements of a sequence.
- It's traditionally used when you have a piece of code which you want to repeat n number of time.
- The syntax of a for loop is:

    for item in list :
      a c t i o n
- As usual, the action consists of one or more statements, all at the same indentation level. These statements are also known as the body of the loop. The item is a variable name, and list is a list.
- Execution of the for loop works by setting the variable successively to each item in the list, and then executing the body each time.

  Here is a simple example:

In [116]:
for i in [2 , 4 , 6 , 0]:
    print(i)

2
4
6
0

In [117]:
for counter in range(1, 6):
    print(counter)

1
2
3
4
5

In [118]:
word = "sara"
for letter in word:
    print(letter)

s
a
r
a

### While loop

In [119]:
a=0
while a < 10:
  a=a+1
  print(a)

1
2
3
4
5
6
7
8
9
10

# 6.Functions

 - You use functions in programming to bundle a set of instructions that you want to use repeatedly or that, because of their  complexity, are better self-contained in a sub-program and called when needed.                                 
 - Function is a piece of code written to carry out a specified task.
 - There are three types of functions in Python:
 - Built-in functions, such as help() to ask for help, min() to get the minimum value, print() to print an object.
 - User-Defined Functions (UDFs), which are functions that users create to help them out.
 - Anonymous functions, which are also called lambda functions because they are not declared with the standard def keyword.
 - The syntax is:

   def functionname(parameters)
    
   "function_docstring"
   
   function_suite
   
   return [expression]

In [120]:
def my_function(name):
  #This prints a passed string into this function
    print(name)
    return;

#Now you can call my_function
my_function("Mary")

Mary

# 7.Lambda Functions

 - The creation of anonymous functions at runtime,using a construct called "lambda"
 - A lambda function is a small anonymous function.
 - A lambda function can take any number of arguments, but can only have one expression.
 - Lambda function does not include return statement,it always contains an expression which is returned.
 - You might want to use lambdas when you don’t want to use a function twice in a program.

   some examples are given:

In [121]:
#Normal Function
def f (x):
  return x**2
print(f(8))

64

In [122]:
times3 = lambda var:var*3
times3(10)

#lamba expressions : another way to write a function in line

30

In [123]:
add = lambda x, y: x + y

print(add(3, 5))

8

## 7.1 Map()

 - Map() function is used with two arguments.Just like: r=map(func,seq)
 - The first argument func is function name and the second is a sequence(list etc)
 - Map functions expects a function object and any number of iterables like list, dictionary, etc.
 - It executes the function_object for each element in the sequence and returns a list of the elements modified by the function  object.

   Example:

In [124]:
sentence = "It is raining cats and dogs"
words = sentence.split()
print(words)

lengths= map(lambda word :len(word), words)

list(lengths)

['It', 'is', 'raining', 'cats', 'and', 'dogs']

[2, 2, 7, 4, 3, 4]

## 7.2 Filter()

 - The filter() method filters the given iterable with the help of a function that tests each element in the iterable to be true or not.
 - The syntax of filter() method is:
      filter(function, iterable)
 - The filter() method takes two parameters:

      1)function - function that tests if elements of an iterable returns true or false If None, the function defaults to Identity function - which returns false if any elements are false
      
      2)iterable - iterable which is to be filtered, could be sets, lists, tuples, or containers of any iterators
 - The filter() method returns an iterator that passed the function check for each element in the iterable.

In [125]:
# list of alphabets
alphabets = ['a', 'b', 'd', 'e', 'i', 'j', 'o']

# function that filters vowels
def filterVowels(alphabet):
    vowels = ['a', 'e', 'i', 'o', 'u']

    if(alphabet in vowels):
        return True
    else:
        return False

for i in filter(filterVowels, alphabets):
     print(i)

a
e
i
o

In [126]:
# random list
randomList = [1, 'a', 0, False, True, '0']

filteredList = filter(None, randomList)

print('The filtered elements are:')
for element in filteredList:
    print(element)

The filtered elements are:
1
a
True
0

In [127]:
ages = [5, 12, 17, 18, 24, 32]

def myFunc(x):
  if x < 18:
    return False
  else:
    return True

adults = filter(myFunc, ages)

for x in adults:
  print(x)

18
24
32

# 8.File I/O

 - In this section we will cover basic I/O functions.

## Reading input from keyboard

 -  There are two functions in Python that you can use to read data from the user:raw_input and input
 -  You can store the results from them into a variable
 -  If the input function is called, the program flow will be stopped until the user has given an input and has ended the input  with the return key. The text of the optional parameter, i.e. the prompt, will be printed on the screen.

 Let's have a look at the following example:

In [128]:
name = raw_input("What's your name? ")
print("Nice to meet you " + name + "!")

NameError: name 'raw_input' is not defined

In [129]:
age = raw_input("What's your age? ")
print("your age is " + age + "!")

NameError: name 'raw_input' is not defined

In [130]:
string=raw_input("enter your university....")
print(string)

NameError: name 'raw_input' is not defined

## I/O From or to text file

 - In this scenario, we will read and write to a text file.
 - we can open files in different modes.

## Read only mode

 - r opens a file in read only mode.
 - The file pointer is placed at the beginning of the file.
 - This is the default mode.

In [131]:

file = open("hello.txt", "r")
str=file.read();
print(str)
file.close()

FileNotFoundError: [Errno 2] No such file or directory: 'hello.txt'

## Read and write mode

 - r+ opens a file in read and write mode.
 - The file pointer placed at the beginning of the file

In [132]:
# Open a file
file = open("hello.txt", "r+")
str = file.read(10);
print "Read String is : ", str
# Close opend

SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)? (593397110.py, line 4)

## Write mode only

 - w opens a file in write mode only.
 - Overwrites the file if the file exists. If the file does not exist, creates a new file for writing

In [133]:
file = open('write.txt','w')
file.write("This is the write command")
file.write("It allows us to write in a particular file")
file = open('write.txt','r')
str=file.read()
print(str)
file.close()

This is the write commandIt allows us to write in a particular file

## Append mode

 - a opens a file in append mode.
 - The file pointer is at the end of the file if the file exists.
 - That is, the file is in the append mode. If the file does not exist, it creates a new file for writing.

In [134]:
file = open('write.txt','a')
file.write("This will add this line")
file = open('write.txt','r')
str=file.read()
print(str)
file.close()

This is the write commandIt allows us to write in a particular fileThis will add this line

## Append and read mode

 - a+ opens a file in append and read mode.
 - The file pointer is at the end of the file if the file exists. The file opens in the append mode. If the file does not exist,    it creates a  new file for reading and writing.

In [135]:
file = open('hello.txt','a+')
file.write("MSCS From comsats university")
file.close()
file = open('hello.txt','r')
str=file.read()
print(str)
file.close()

MSCS From comsats university

## File Position

 - tells() method tells the current position within the file.
 - seek() method changes the current file method.
 - Following is the syntax for seek() method:    fileObject.seek(offset[, whence])

In [136]:
f = open('hello.txt',"r+")
str=f.read(20);
print("read string is :",str)

position=f.tell();
print("current file position is :",position)

position=f.seek(5);
str=f.read(10);
print("again read string is :",str)
f.close()

read string is : MSCS From comsats un
current file position is : 20
again read string is : From comsa

# 9.Pandas Introduction

Pandas is an open-source Python Library providing high-performance data manipulation and analysis tool using its powerful data structures. The name Pandas is derived from the word Panel Data – an Econometrics from Multidimensional data. In 2008, developer Wes McKinney started developing pandas when in need of high performance, flexible tool for analysis of data.

Prior to Pandas, Python was majorly used for data munging and preparation. It had very less contribution towards data analysis. Pandas solved this problem. Using Pandas, we can accomplish five typical steps in the processing and analysis of data, regardless of the origin of data — load, prepare, manipulate, model, and analyze.

Python with Pandas is used in a wide range of fields including academic and commercial domains including finance, economics, Statistics, analytics, etc.

#### Key Features of Pandas

-  Fast and efficient DataFrame object with default and customized indexing.
-  Tools for loading data into in-memory data objects from different file formats.
-  Data alignment and integrated handling of missing data.
-  Reshaping and pivoting of date sets.
- Label-based slicing, indexing and subsetting of large data sets.
- Columns from a data structure can be deleted or inserted.
- Group by data for aggregation and transformations.
- High performance merging and joining of data.
- Time Series functionality.

Pandas deals with the following three data structures:
- Series
- DataFrame
- Panel

These data structures are built on top of Numpy array, which means they are fast.

# 10.Series

- The Series is a one-dimensional array that can store various data types, including mix data types.
- The row labels in a Series are called the index.
- Any list, tuple and dictionary can be converted in to Series using ‘series’ method
- Basic method to create a series: s = pd.Series(data, index = index)
- Series is size immutable.

In [137]:
import pandas as pd
s = pd.Series([1, 'Lahore', 2, 3, 'Happy Eating!'])
s

0                1
1           Lahore
2                2
3                3
4    Happy Eating!
dtype: object

## 10.1 Series creation from ndarray

- Index must be of same length as data. If no index is passed, it will automatically be [0, ..., len(data) - 1]

In [138]:
first_series = pd.Series([1,2,4,8,16,32,64])
print(type(first_series))
print(first_series)

<class 'pandas.core.series.Series'>
0     1
1     2
2     4
3     8
4    16
5    32
6    64
dtype: int64

In [139]:
import numpy as np
s = pd.Series(np.random.randn(5), index=['a', 'b', 'c', 'd', 'e'])
print(s)
print('-'*50)
print(s.index)

a   -1.593016
b   -0.097023
c   -0.281029
d   -1.253950
e    0.854559
dtype: float64
--------------------------------------------------
Index(['a', 'b', 'c', 'd', 'e'], dtype='object')

## 10.2 Series creation from dict

- If Data is a dictionary, if index is passed the values in data corresponding to the labels in the index will be pulled out, otherwise an index will be constructed from the sorted keys of the dict.

In [140]:
d = {'a': 100., 'b': 200., 'c': 300.}
pd.Series(d)

a    100.0
b    200.0
c    300.0
dtype: float64

In [141]:
data = {'abc': 1, 'def': 2, 'xyz': 3}
pd.Series(data)

abc    1
def    2
xyz    3
dtype: int64

## 10.3 Series creation from a scalar value

- Index must be provided. The value will be repeated to match the length of the index

In [142]:
pd.Series(5, index = ['a', 'b', 'c'])

a    5
b    5
c    5
dtype: int64

In [143]:
 x = pd.Series(3, index=['a', 'b', 'c', 'd'])
x

a    3
b    3
c    3
d    3
dtype: int64

## 10.4 Series is ndarray-like

- Series acts similar to a numpy array, and is valid arguments to most numpy functions.
- Slicing also slices the index
- Short Intro, back to this later

In [144]:
s = pd.Series(np.random.randn(5), index=['a', 'b', 'c', 'd', 'e'])
print(s)

a   -0.936536
b    1.556925
c    0.827804
d    1.393992
e    0.520589
dtype: float64

In [145]:
s = pd.Series(np.random.randn(5), index=['a', 'b', 'c', 'd', 'e'])
print(s.iloc([2,1,4]))

TypeError: unhashable type: 'list'

In [ ]:
s = pd.Series(np.random.randn(5), index=['a', 'b', 'c', 'd', 'e'])
print(s[:3])

In [ ]:
s = pd.Series(np.random.randn(5), index=['a', 'b', 'c', 'd', 'e'])
print(s[[3,2,1]])

In [ ]:
s = pd.Series(np.random.randn(5), index=['a', 'b', 'c', 'd', 'e'])
np.exp(s)

In [ ]:
s = pd.Series(np.random.randn(5), index=['a', 'b', 'c', 'd', 'e'])
s['b']

In [ ]:
s = pd.Series(np.random.randn(5), index=['a', 'b', 'c', 'd', 'e'])
s['b']=12.
s

In [ ]:
s = pd.Series(np.random.randn(5), index=['a', 'b', 'c', 'd', 'e'])
'e' in s

In [ ]:
s = pd.Series(np.random.randn(5), index=['a', 'b', 'c', 'd', 'e'])
'f' in s

## 10.5 Series is dict-like

- A Series is like a xed-size dict in that you can get and set values by index label

In [ ]:
s = pd.Series([1, 2, 3, 4])
s.to_dict()

## 10.6 Vectorized operations and label alignment with Series

- When doing data analysis,as with the row NumPy arrays looping through series value by value is usually not necessary.
- Series can also be passed into most NumPy method expecting an ndarray.
- NumPy and Pandas generalize arithmetic operations so that we can easily and quickly perform the same operation on many array elements. For example:

In [ ]:
import numpy as np
x = np.array([2, 3, 5, 7, 11, 13])
x * 2

In [ ]:
data = ['saima', 'aisha', 'faiza', 'saira']
[s.capitalize() for s in data]

# 11.Data Frames

- A DataFrame is a two dimensional object that can have columns with potential different types. Different kind of inputs include dictionaries, lists, series, and even another DataFrame.
- It is the most commonly used pandas object.
- You can create a series from:
    - Dict of 1D ndarrays, lists, dicts, or Series
    - 2-D numpy array
    - A list of dictionaries
    - A Series
    - Another Dataframe
  
- index/ columns is a list of the row/ column labels. If you pass an index and/ or columns, you are guarenteeing the index and /or column of the df.
- If you do not pass anything in, the input will be constructed by "common sense" rules

In [ ]:
dates = pd.date_range('20130101',periods=6)
dates

## 11.1 Dataframe creation from dict of series or dicts

 - The index of the resulting DataFrame will be the union of the indices of the various Series. If there are any nested dicts, these will be converted to Series.
 - If no columns are passed, the columns will be the sorted list of dict keys.

In [ ]:
# Create a dictionary of series
d = {'one': pd.Series([1,2,3], index = ['a', 'b', 'c']),
'two': pd.Series(list(range(4)), index = ['a','b', 'c', 'd'])}
# Columns are dictionary keys, indices and values obtained from series
df = pd.DataFrame(d)
# Notice how it fills the column one with NaN for d
print(df)

In [ ]:
 d = {'col1': [1, 2], 'col2': [3, 4]}
 df = pd.DataFrame(data=d)
 df

## 11.2  Dataframe creation from dict of ndarrays/lists

 - The ndarrays must all be the same length.
 - If an index is passed, it must clearly also be the same length as the arrays. If no index is passed, the result will be range(n), where n is the array length.

In [ ]:
d = {'one' : [1., 2., 3., 4.], 'two' : [4., 3., 2., 1.]}
pd.DataFrame(d)

In [ ]:
df2 = pd.DataFrame(np.random.randint(low=0, high=10, size=(5, 5)), columns=['a', 'b', 'c', 'd', 'e'])
df2

## 11.3 Dataframe creation from a list of dicts

In [ ]:
data = [{'a':10,"b":20},{'a':5,'b':10,'c':20}]
pd.DataFrame(data)

In [ ]:
data = [{'a':10,"b":20,"c":30},{'a':5,'b':10,'c':20}]
pd.DataFrame(data)

## 11.4 Dataframe creation from a dict of tuples

 - You can automatically create a multi indexed by passing a tuple dictionary.

In [ ]:

df = pd.DataFrame({'Initial': ['C','A','M'], 'Sex': ['M', 'F', 'F'], 'Age': [49, 39, 19]})
#df = df[['Initial', 'Sex', 'Age']]
df

In [ ]:
data = [('p1', 't1', 1, 2),('p1', 't2', 3, 4),('p2', 't1', 5, 6),('p2', 't2', 7, 8),('p2', 't3', 2, 8)]

df = pd.DataFrame(data)
df

## 11.5 Alternate constructors

### Dataframe.from_dict

 - Dataframe.from_dict takes a dict of dictsor a dict of array like sequences and returns a Dataframe.
 - It operates like the dataframe constructor except for the orient parameter which is coulmn by default,but which can be set to index in order to use the dict keys as row labels.

In [ ]:
data = {"X": {'a': 1, 'b': 2, 'c': 3}, "Y": {'d': 4, 'e': 5, 'f': 6}, "Z": {'g': 7, 'h': 8, 'i': 9}}

df = pd.DataFrame.from_dict(data, orient="index").fillna(0).astype(int)
df

### Dataframe.from_records

- Dataframe.from_records take a list of tuples or an ndarray with structured dtype.
- Works analogously to the normal dataframe constructor,except that index may be aspecific field of the structured dtype to use as the index.for example:

In [ ]:
sales = [('Jones LLC', 150, 200, 50),
     ('Alpha Co', 200, 210, 90),
     ('Blue Inc', 140, 215, 95)]
labels = ['account', 'Jan', 'Feb', 'Mar']
df = pd.DataFrame.from_records(sales, columns=labels)
df

### Dataframe.from_items

- Convert (key, value) pairs to DataFrame. The keys will be the axis index (usually the columns, but depends on the specified orientation). The values should be arrays or Series.

In [ ]:
df=pd.DataFrame.from_items([('A',[1,2,3]),('B',[4,5,6])]

In [ ]:
df=pd.DataFrame.from_items([('A',[1,2,3]),('B',[4,5,6])])
df

## 11.6 Column selection,addition,deletion

 - You can treat a DataFrame semantically like a dict of like-indexed Series objects. Getting, setting, and deleting columns works with the same syntax as the analogous dict operations:

In [ ]:
df = pd.DataFrame([[1,2],[3,4],[5,6]], columns=['a','a']) # you can adress column by index
df

In [ ]:
df = pd.DataFrame([[1,2],[3,4],[5,6]], columns=['a','a'])
df.columns = ['a','b']  # rename column
df

In [ ]:
df = pd.DataFrame([[1,2],[3,4],[5,6]], columns=['a','b'])
del df['b']   # delete column
df

In [ ]:
df = pd.DataFrame([[1,2],[3,4],[5,6]], columns=['a','b'])
df['c']='2'   #add new column c and fill with 2
df

### 11.7 Indexing / seletion

- Row selection, for example, returns a Series whose index is the columns of the DataFrame:
- Pandas now supports three types of Multi-axes indexing; the three types are:
    - .loc()  (label based)
    - .iloc()  (integer based)
    - .ix()    (both label and integer based)
- loc takes two single/list/range operator separated by ','. The first one indicates the row and the second one indicates columns.
- iloc(): Pandas provide various methods in order to get purely integer based indexing. Like python and numpy, these are 0-based indexing.
- ix(): Besides pure label based and integer based, Pandas provides a hybrid method for selections and subsetting the object using the .ix() operator.

#### .loc()

In [ ]:
df = pd.DataFrame(np.random.randn(8, 4),
index = ['a','b','c','d','e','f','g','h'], columns = ['A', 'B', 'C', 'D'])

#select all rows for a specific column
print(df.loc[:,'A'])

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.DataFrame(np.random.randn(8, 4),
index = ['a','b','c','d','e','f','g','h'], columns = ['A', 'B', 'C', 'D'])

# Select all rows for multiple columns, say list[]
print(df.loc[:,['A','C']])

In [ ]:
df = pd.DataFrame(np.random.randn(8, 4),
index = ['a','b','c','d','e','f','g','h'], columns = ['A', 'B', 'C', 'D'])

# Select range of rows for all columns
print(df.loc['a':'h'])

#### .iloc()

In [ ]:
df = pd.DataFrame(np.random.randn(8, 4), columns = ['A', 'B', 'C', 'D'])

# select all rows for a specific column
print(df.iloc[:4])

In [ ]:
df = pd.DataFrame(np.random.randn(8, 4), columns = ['A', 'B', 'C', 'D'])

# Integer slicing

print(df.iloc[1:5, 2:4])

#### .ix()

In [ ]:
df = pd.DataFrame(np.random.randn(8, 4), columns = ['A', 'B', 'C', 'D'])

# Integer slicing
print(df.ix[:4])

In [ ]:
df = pd.DataFrame(np.random.randn(8, 4), columns = ['A', 'B', 'C', 'D'])
# Index slicing
print(df.ix[:,'A'])

## 11.8 Data alignment and arithmetic

 - Data alignment between DataFrame objects automatically align on both the columns and the index (row labels).
 - Again, the resulting object will have the union of the column and row labels.

In [146]:
df1 = pd.DataFrame(np.random.randn(10, 4), columns=['A', 'B', 'C', 'D'])
df1

          A         B         C         D
0  0.020533 -0.775320  1.336585 -1.710158
1  1.276539  0.283304 -2.057938 -1.349279
2 -1.938568  0.795129 -0.439927 -0.235025
3 -0.453479  1.035982 -0.734541  0.890598
4 -1.094633 -0.403921  0.895650  0.292180
5  0.815574  2.006845  0.448654  1.050606
6  0.528357 -0.801604  0.758919  1.377605
7  1.139834  0.272960 -0.558191 -0.642545
8 -0.582988  0.741485 -0.495784  0.505454
9  1.550959  0.337628 -1.484911 -1.229964

In [147]:

df2 = pd.DataFrame(np.random.randn(7, 3), columns=['A', 'B', 'C'])
df2

          A         B         C
0  0.302009 -0.959077 -1.091591
1  0.227041  0.793710  0.167290
2  0.541945  0.700044 -0.071115
3 -1.204538  1.599614  2.459614
4 -0.711824  0.071197  0.823833
5  0.804055 -0.384551 -1.427555
6 -0.519190  0.168440 -0.322692

In [148]:
df1+df2

          A         B         C   D
0  0.322542 -1.734397  0.244994 NaN
1  1.503580  1.077014 -1.890648 NaN
2 -1.396623  1.495173 -0.511042 NaN
3 -1.658016  2.635596  1.725073 NaN
4 -1.806456 -0.332724  1.719483 NaN
5  1.619629  1.622294 -0.978901 NaN
6  0.009168 -0.633165  0.436227 NaN
7       NaN       NaN       NaN NaN
8       NaN       NaN       NaN NaN
9       NaN       NaN       NaN NaN

- When doing an operation between DataFrame and Series, the default behavior is to align the Series index on the DataFrame columns, thus broadcasting row-wise. For example:

In [149]:
df1 - df1.iloc[0]

          A         B         C         D
0  0.000000  0.000000  0.000000  0.000000
1  1.256006  1.058624 -3.394523  0.360880
2 -1.959101  1.570449 -1.776512  1.475133
3 -0.474012  1.811301 -2.071127  2.600756
4 -1.115166  0.371399 -0.440935  2.002338
5  0.795041  2.782165 -0.887932  2.760764
6  0.507824 -0.026285 -0.577667  3.087764
7  1.119301  1.048280 -1.894777  1.067614
8 -0.603521  1.516804 -1.832370  2.215612
9  1.530426  1.112947 -2.821497  0.480194

 - In the special case of working with time series data, and the DataFrame index also contains dates, the broadcasting will be column-wise:

In [150]:
index = pd.date_range('1/1/2000', periods=8)
df = pd.DataFrame(np.random.randn(8, 3), index=index, columns=list('ABC'))
df

                   A         B         C
2000-01-01  0.709579 -0.643742  0.451054
2000-01-02  0.460222  0.182252 -1.080684
2000-01-03  0.434038  0.272172 -0.605007
2000-01-04 -0.579499  0.043875  0.357973
2000-01-05 -0.699242 -0.644054  0.150002
2000-01-06  0.426466 -0.236632  0.523144
2000-01-07  0.312072  0.174431  0.248051
2000-01-08  1.267649  0.957642 -0.811293

In [151]:
df1* 10 + 2

           A          B          C          D
0   2.205330  -5.753197  15.365855 -15.101583
1  14.765390   4.833042 -18.579376 -11.492787
2 -17.385679   9.951291  -2.399267  -0.350251
3  -2.534788  12.359818  -5.345412  10.905975
4  -8.946326  -2.039208  10.956501   4.921798
5  10.155742  22.068450   6.486537  12.506056
6   7.283574  -6.016045   9.589190  15.776054
7  13.398341   4.729600  -3.581912  -4.425447
8  -3.829876   9.414847  -2.957842   7.054536
9  17.509585   5.376277 -12.849115 -10.299645

In [152]:
1/df1

           A         B         C         D
0  48.702066 -1.289791  0.748175 -0.584741
1   0.783368  3.529774 -0.485923 -0.741137
2  -0.515845  1.257657 -2.273106 -4.254865
3  -2.205175  0.965268 -1.361394  1.122842
4  -0.913549 -2.475733  1.116507  3.422550
5   1.226130  0.498295  2.228890  0.951832
6   1.892658 -1.247498  1.317664  0.725897
7   0.877321  3.663541 -1.791501 -1.556312
8  -1.715302  1.348645 -2.017007  1.978421
9   0.644763  2.961842 -0.673441 -0.813032

In [153]:
df1**5

              A          B          C          D
0  3.649750e-09  -0.280159   4.265635 -14.627885
1  3.389772e+00   0.001825 -36.911444  -4.472067
2 -2.737821e+01   0.317825  -0.016478  -0.000717
3 -1.917720e-02   1.193330  -0.213836   0.560283
4 -1.571600e+00  -0.010752   0.576357   0.002129
5  3.608423e-01  32.551361   0.018178   1.279967
6  4.117550e-02  -0.330979   0.251754   4.961629
7  1.924014e+00   0.001515  -0.054189  -0.109526
8 -6.734365e-02   0.224136  -0.029955   0.032992
9  8.974308e+00   0.004387  -7.219428  -2.814899

- Boolean operators work as well:

In [154]:
df1 = pd.DataFrame({'a' : [1, 0, 1], 'b' : [0, 1, 1] }, dtype=bool)
df1

       a      b
0   True  False
1  False   True
2   True   True

In [155]:
df2 = pd.DataFrame({'a' : [0, 1, 1], 'b' : [1, 1, 0] }, dtype=bool)
df2

       a      b
0  False   True
1   True   True
2   True  False

In [156]:
df1&df2

       a      b
0  False  False
1  False   True
2   True  False

In [157]:
df1 | df2

      a     b
0  True  True
1  True  True
2  True  True

In [158]:
df1^df2

       a      b
0   True   True
1   True  False
2  False   True

In [159]:
-df1

       a      b
0  False   True
1   True  False
2  False  False

## 11.9 transposing

- To transpose, access the T attribute (also the transpose function), similar to an ndarray:

In [160]:
# only show the first 4 rows
df[:4].T

   2000-01-01  2000-01-02  2000-01-03  2000-01-04
A    0.709579    0.460222    0.434038   -0.579499
B   -0.643742    0.182252    0.272172    0.043875
C    0.451054   -1.080684   -0.605007    0.357973